### ISSUE TITLE
moar encoding headaches

### ISSUE THREAD

**Issue by vbatts** [vbatts/slack-utils#8]
ArgumentError: invalid byte sequence in US-ASCII
    from /home/vbatts/svn/slack-utils/src/lib/slackware/package.rb:168:in `block in get_owned_files'
    from /home/vbatts/svn/slack-utils/src/lib/slackware/package.rb:164:in`open'
    from /home/vbatts/svn/slack-utils/src/lib/slackware/package.rb:164:in `get_owned_files'
    from /home/vbatts/svn/slack-utils/src/lib/slackware/system.rb:202:in`block in owns_file'
    from /home/vbatts/svn/slack-utils/src/lib/slackware/system.rb:201:in `each'
    from /home/vbatts/svn/slack-utils/src/lib/slackware/system.rb:201:in`owns_file'

**Comment by vbatts** [comment]
wrapping the problem areas.
and adding it to the debug logging
